Draft: RateLimiter - consider whole operation execution time
softwaremill/ox pull request #251
Opened 2024-12-09 16:12 UTC by Kamil-Lontkowski

Closes #246

2024-12-10 07:45 UTC, adamw commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +      synchronized:
we can't (and shouldn't) use `synchronized` in Loom (at least until JDK25). Besides, all synchronization is done using semaphores, so this shouldn't be necessary

2024-12-10 07:54 UTC, adamw commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +class RateLimiter private (algorithm: RateLimiterAlgorithm, considerOperationTime: Boolean):
maye instead of a boolean flag we could have an enum, sth like `RateLimiterMode` with `OperationStart` and `OperationDuration` values. This should be clearer for users

2024-12-10 08:00 UTC, adamw commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +    if considerOperationTime then
an option to explore: instead of if-else, maybe the operation-time rate limiters should be another `Algorithm` implementations? (with some extensions to the algorithm interface)

2024-12-10 08:11 UTC, adamw commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +  def leakyBucket(maxTokens: Int, refillInterval: FiniteDuration, considerOperationTime: Boolean = false)(using Ox): RateLimiter =
does leaky bucket make sense with whole-operation-time mode?

2024-12-10 12:51 UTC, Kamil-Lontkowski commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +  def leakyBucket(maxTokens: Int, refillInterval: FiniteDuration, considerOperationTime: Boolean = false)(using Ox): RateLimiter =
In leaky bucket we have `Semaphore(1)` and it's released every `per`(if it lower than rate). So we still can have case where we submit long operation, then the bucket refill and let us submit another operation while first is still running. At least I understand it that way looking at `LeakyBucket` code.

2024-12-10 13:02 UTC, Kamil-Lontkowski commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +    if considerOperationTime then
I started with that option, but in the end it produced a duplicated algorithms with logic that is now in `runOrDrop` and `runBlocking` in different places. Currently when we want to track execution time we have two semaphores that can block independently, so for now I don't see a reason to move this logic to `RateLimiterAlgorithm`, maybe with different algorithms it would need to be done this way, but for now I think this is better option.

2024-12-10 14:53 UTC, adamw commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +  private val semaphore = new Semaphore(algorithm.rate)
I don't think that's a correct solution. If I understand this correctly, the main change is adding a semaphore which causes that at most `rate` computations run concurrently. But rate limiting is about time, which is not present here at all.

Suppose we use the fixed-window rate limiter, with a limit of 2 ops/second. Consider this scenario:
1. we start two operations at t=900ms; they will take 200ms
2. at t=1000ms, we replenish the permits (as the algorithm specifies)
3. at t=1100ms, the two operations finish, and we release the `semaphore`
4. at t>1100ms, we can start a new operations, but we shouldn't be able to - with `OperationDuration` we should consider the whole operation's time, including the fact that it spanned two windows, so both of these might as well have actually happened in the second time window

For the next iteration, please also provide an explanation of your approach, and why it works

2024-12-12 16:04 UTC, uini223 requested changes

2024-12-12 16:04 UTC, uini223 commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +  def fixedWindow(maxOperations: Int, window: FiniteDuration, operationMode: RateLimiterMode = RateLimiterMode.OperationStart)(using
I'm not sure if we need those extensions here. 
Overall we have DurationRateLimiter with factory methods and imho it should be enough. 

We don't want to change the behaviour of those methods anyway. 

I would additionally add info in the docs that this is operation start based and for duration based see other.

2024-12-12 21:09 UTC, Kamil-Lontkowski commented on core/src/main/scala/ox/resilience/DurationRateLimiterAlgorithm.scala
> +      val _ = log.updateAndGet(qNew =>
This is still kind of WIP, but this was copied from RateLimiterAlgorithm. I guess it was just another way for the last expression to be Unit. I will refactor this to be consistent.

2024-12-12 21:11 UTC, Kamil-Lontkowski commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +      case alg: DurationRateLimiterAlgorithm =>
Yes, I was having trouble with coming up with sensible interface. I think that'll be better solution.

2024-12-12 21:19 UTC, Kamil-Lontkowski commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +  def fixedWindow(maxOperations: Int, window: FiniteDuration, operationMode: RateLimiterMode = RateLimiterMode.OperationStart)(using
According to previous comment. If we just change RateLimiter and use:
```scala
algorithm.acquire()
alogrithm.runOperation(operation)
```
I don't think we then need DurationRateLimiter, we just change the algorithm provided to RateLimiter. If we go this route I think extensions that let you define RateLimter with DurationRateLimiterAlgorithm would be useful. Maybe new methods instead of extending existing ones.

2024-12-16 08:41 UTC, Kamil-Lontkowski commented
Considering [comment](https://github.com/softwaremill/ox/pull/251#discussion_r1878249002).

`DurationRateLimiterAlgorithm.FixedWindow` tracks number of running operations and doesn't replenish number of permits that running operations are "blocking".

`DurationRateLimiterAlgorithm.SlidingWindow` adds entry to log only after the operation is finished. This means that we consider end of operation as a point where we can replenish permits after `per` passes.

These changes mean that fixed window behaves in example as specified in [the comment](https://github.com/softwaremill/ox/pull/251#discussion_r1878249002]).

For sliding window consider this example:
We have three types of operations - instant, short(300 millis), long (3 seconds)
```scala
val rateLimiter = RateLimiter.slidingWindow(3, FiniteDuration(1, "second"), OperationDuration)

forkUserDiscard:
  result1 = rateLimiter.runOrDrop(shortOperation)
forkUserDiscard:
  result2 = rateLimiter.runOrDrop(shortOperation)
forkUserDiscard:
  result3 = rateLimiter.runOrDrop(longOperation)
forkUserDiscard:
  sleep(1500.millis)
  result4 = rateLimiter.runOrDrop(instantOperation)
  result5 = rateLimiter.runOrDrop(instantOperation)
  result6 = rateLimiter.runOrDrop(instantOperation)
```
After 1.5 second, two of three operations ended(at 0.3 seconds, so one full second passed since then), so we should have 2 available permits. Since at this point long operation is still running, we drop last operation and `result6` is None

2024-12-16 10:41 UTC, adamw commented on core/src/main/scala/ox/resilience/DurationRateLimiterAlgorithm.scala
> +      semaphore.release(rate - semaphore.availablePermits() - runningOperations.get())
let's add a comment here, why we calculate the permits to release this way

2024-12-16 10:42 UTC, adamw commented on core/src/main/scala/ox/resilience/DurationRateLimiterAlgorithm.scala
> +      runningOperations.updateAndGet(current => (current - permits).max(0))
I guess this should never fall below 0? and if it does, that's a bug? if so, maybe let's add an assert here

2024-12-16 10:42 UTC, adamw commented on core/src/main/scala/ox/resilience/DurationRateLimiterAlgorithm.scala
> +object DurationRateLimiterAlgorithm:
lets add a comment here describing how this differs from `RateLimiterAlgorithm`

2024-12-16 10:42 UTC, adamw commented on core/src/main/scala/ox/resilience/DurationRateLimiterAlgorithm.scala
> +  /** Fixed window algorithm: allows to run at most `rate` operations in consecutively segments of duration `per`. */
that comment is incomplete - please self-review comments

2024-12-16 10:56 UTC, adamw commented
@Kamil-Lontkowski thanks, this looks much better. I left some comments - I think it's especially worthwhile describing how the modified algorithms work (for our future selves :) ), and how they differ from the other mode counterparts.

2024-12-16 10:56 UTC, uini223 commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +  def leakyBucket(maxTokens: Int, refillInterval: FiniteDuration, considerOperationTime: Boolean = false)(using Ox): RateLimiter =
We discussed it with @Kamil, and we came to conclusion that it doesn't make much sense. 
Effectively it would result in "max number of operations currently running"

2024-12-16 10:57 UTC, adamw commented
And yes, I think the token bucket only makes sense in the original mode

2024-12-16 11:04 UTC, uini223 commented on core/src/main/scala/ox/resilience/DurationRateLimiterAlgorithm.scala
> +object DurationRateLimiterAlgorithm:
I would also add info that we did not implement LeakyBucket on purpose

2024-12-16 11:25 UTC, uini223 commented on core/src/main/scala/ox/resilience/DurationRateLimiterAlgorithm.scala
> +      runningOperations.updateAndGet(current => (current - permits).max(0))
> also, this should be in a finally
Also in Sliding window

2024-12-16 11:29 UTC, uini223 commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +  def fixedWindow(maxOperations: Int, window: FiniteDuration, operationMode: RateLimiterMode = RateLimiterMode.OperationStart)(using
So I see that we have 3 options here:
1. Leave it as it is (with Enum as additional parameter)
2. Add new methods in this class e.g. durationFixedWindow
3. Add DurationRateLimiter just to have factory methods `fixedWindow` and `durationWindow` 

For me number 3 should do the job, but that's a bit matter of style. 
@adamw Wdyt?

2024-12-16 11:30 UTC, uini223 submitted a review, later dismissed

2024-12-16 12:10 UTC, adamw commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +  def fixedWindow(maxOperations: Int, window: FiniteDuration, operationMode: RateLimiterMode = RateLimiterMode.OperationStart)(using
I think I'd keep `RateLimiter` as the single entry point. But separate methods are probably better, as it's an entirely different operation. So let's go with 2.

2024-12-16 17:47 UTC, Kamil-Lontkowski commented on core/src/main/scala/ox/resilience/DurationRateLimiterAlgorithm.scala
> +      semaphore.release(rate - semaphore.availablePermits() - runningOperations.get())
Added

2024-12-16 17:47 UTC, Kamil-Lontkowski commented on core/src/main/scala/ox/resilience/DurationRateLimiterAlgorithm.scala
> +object DurationRateLimiterAlgorithm:
Added

2024-12-16 17:48 UTC, Kamil-Lontkowski commented on core/src/main/scala/ox/resilience/RateLimiter.scala
> +  def fixedWindow(maxOperations: Int, window: FiniteDuration, operationMode: RateLimiterMode = RateLimiterMode.OperationStart)(using
I added new methods

2024-12-17 16:51 UTC, merged

2024-12-17 16:53 UTC, adamw commented
Thanks! :)